### ISSUE TITLE
still plans to develop this further?

### ISSUE THREAD

**Issue by felixroos** [Mrtenz/soundfont2#2]
I wonder if there are any plans to develop this project further?
Currently, I am developing a basic sf2 synth based on this, but I see some generators are not turned into properties yet.
Would you accept PRs? I would love to have a solid sf2 synth for my pet project [strudel](https://strudel.tidalcycles.org/)

**Comment by Mrtenz** [comment]
I currently don't have the time or need to actively maintain this project, since I'm not really using SF2 anymore. But I'm happy to accept PRs!

**Comment by felixroos** [comment]
ok ! just opened https://github.com/Mrtenz/soundfont2/pull/3 . It would be super nice if you can take a look :)

**Comment by this-fifo** [comment]
Hey @felixroos — would you be willing to share more about the implementation of your sf2 synth based on this? I have the same needs and am very curious about how to use this library for that.

For now I have been using something a lot more manual through pre-rendering soundfonts to load in a sampler synth — You can read more about it on [this other issue](https://github.com/danigb/smplr/issues/78)

Ideally I would rather use the raw soundfont without needing to pre-render it into samples, is that how you're doing?

PS: I absolutely love Strudel, what an incredibly amazing project. I need to learn more about it and start writing some tunes there, really awesome work you've done there!

**Comment by this-fifo** [comment]
Actually @felixroos, I just came across your project `sfumato` — incredible work btw — and it looks like this is where it gets used?

- https://github.com/felixroos/sfumato/blob/main/src/index.ts

Let me know if I'm on the right track and/or you have other insights to share related to implementing and using this, love your work truly inspiring!
